// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tunnel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelMessage_Register
	//	*TunnelMessage_RegisterAck
	//	*TunnelMessage_Open
	//	*TunnelMessage_Data
	//	*TunnelMessage_Close
	//	*TunnelMessage_Ping
	//	*TunnelMessage_Pong
	Payload       isTunnelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetPayload() isTunnelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *TunnelMessage) GetRegisterAck() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *TunnelMessage) GetOpen() *TcpOpen {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *TunnelMessage) GetData() *TcpData {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelMessage) GetClose() *TcpClose {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *TunnelMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *TunnelMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isTunnelMessage_Payload interface {
	isTunnelMessage_Payload()
}

type TunnelMessage_Register struct {
	// Registration
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type TunnelMessage_RegisterAck struct {
	RegisterAck *RegisterResponse `protobuf:"bytes,2,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type TunnelMessage_Open struct {
	// TCP stream control
	Open *TcpOpen `protobuf:"bytes,10,opt,name=open,proto3,oneof"`
}

type TunnelMessage_Data struct {
	Data *TcpData `protobuf:"bytes,11,opt,name=data,proto3,oneof"`
}

type TunnelMessage_Close struct {
	Close *TcpClose `protobuf:"bytes,12,opt,name=close,proto3,oneof"`
}

type TunnelMessage_Ping struct {
	// Health check
	Ping *Ping `protobuf:"bytes,30,opt,name=ping,proto3,oneof"`
}

type TunnelMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,31,opt,name=pong,proto3,oneof"`
}

func (*TunnelMessage_Register) isTunnelMessage_Payload() {}

func (*TunnelMessage_RegisterAck) isTunnelMessage_Payload() {}

func (*TunnelMessage_Open) isTunnelMessage_Payload() {}

func (*TunnelMessage_Data) isTunnelMessage_Payload() {}

func (*TunnelMessage_Close) isTunnelMessage_Payload() {}

func (*TunnelMessage_Ping) isTunnelMessage_Payload() {}

func (*TunnelMessage_Pong) isTunnelMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subdomain     string                 `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	BackendHost   string                 `protobuf:"bytes,2,opt,name=backend_host,json=backendHost,proto3" json:"backend_host,omitempty"`
	BackendPort   int32                  `protobuf:"varint,3,opt,name=backend_port,json=backendPort,proto3" json:"backend_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *RegisterRequest) GetBackendHost() string {
	if x != nil {
		return x.BackendHost
	}
	return ""
}

func (x *RegisterRequest) GetBackendPort() int32 {
	if x != nil {
		return x.BackendPort
	}
	return 0
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssignedSubdomain string                 `protobuf:"bytes,1,opt,name=assigned_subdomain,json=assignedSubdomain,proto3" json:"assigned_subdomain,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error             string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAssignedSubdomain() string {
	if x != nil {
		return x.AssignedSubdomain
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TcpOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpOpen) Reset() {
	*x = TcpOpen{}
	mi := &file_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpOpen) ProtoMessage() {}

func (x *TcpOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpOpen.ProtoReflect.Descriptor instead.
func (*TcpOpen) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *TcpOpen) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type TcpData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpData) Reset() {
	*x = TcpData{}
	mi := &file_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpData) ProtoMessage() {}

func (x *TcpData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpData.ProtoReflect.Descriptor instead.
func (*TcpData) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *TcpData) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TcpData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TcpClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpClose) Reset() {
	*x = TcpClose{}
	mi := &file_proto_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpClose) ProtoMessage() {}

func (x *TcpClose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpClose.ProtoReflect.Descriptor instead.
func (*TcpClose) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *TcpClose) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TcpClose) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{7}
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\x06tunnel\"\xd0\x02\n" +
	"\rTunnelMessage\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x17.tunnel.RegisterRequestH\x00R\bregister\x12=\n" +
	"\fregister_ack\x18\x02 \x01(\v2\x18.tunnel.RegisterResponseH\x00R\vregisterAck\x12%\n" +
	"\x04open\x18\n" +
	" \x01(\v2\x0f.tunnel.TcpOpenH\x00R\x04open\x12%\n" +
	"\x04data\x18\v \x01(\v2\x0f.tunnel.TcpDataH\x00R\x04data\x12(\n" +
	"\x05close\x18\f \x01(\v2\x10.tunnel.TcpCloseH\x00R\x05close\x12\"\n" +
	"\x04ping\x18\x1e \x01(\v2\f.tunnel.PingH\x00R\x04ping\x12\"\n" +
	"\x04pong\x18\x1f \x01(\v2\f.tunnel.PongH\x00R\x04pongB\t\n" +
	"\apayload\"u\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tsubdomain\x18\x01 \x01(\tR\tsubdomain\x12!\n" +
	"\fbackend_host\x18\x02 \x01(\tR\vbackendHost\x12!\n" +
	"\fbackend_port\x18\x03 \x01(\x05R\vbackendPort\"q\n" +
	"\x10RegisterResponse\x12-\n" +
	"\x12assigned_subdomain\x18\x01 \x01(\tR\x11assignedSubdomain\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\".\n" +
	"\aTcpOpen\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"B\n" +
	"\aTcpData\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"T\n" +
	"\bTcpClose\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong2K\n" +
	"\rTunnelService\x12:\n" +
	"\x06Tunnel\x12\x15.tunnel.TunnelMessage\x1a\x15.tunnel.TunnelMessage(\x010\x01B/Z-github.com/kaenova/http-tunnels/internal/grpcb\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tunnel_proto_goTypes = []any{
	(*TunnelMessage)(nil),    // 0: tunnel.TunnelMessage
	(*RegisterRequest)(nil),  // 1: tunnel.RegisterRequest
	(*RegisterResponse)(nil), // 2: tunnel.RegisterResponse
	(*TcpOpen)(nil),          // 3: tunnel.TcpOpen
	(*TcpData)(nil),          // 4: tunnel.TcpData
	(*TcpClose)(nil),         // 5: tunnel.TcpClose
	(*Ping)(nil),             // 6: tunnel.Ping
	(*Pong)(nil),             // 7: tunnel.Pong
}
var file_proto_tunnel_proto_depIdxs = []int32{
	1, // 0: tunnel.TunnelMessage.register:type_name -> tunnel.RegisterRequest
	2, // 1: tunnel.TunnelMessage.register_ack:type_name -> tunnel.RegisterResponse
	3, // 2: tunnel.TunnelMessage.open:type_name -> tunnel.TcpOpen
	4, // 3: tunnel.TunnelMessage.data:type_name -> tunnel.TcpData
	5, // 4: tunnel.TunnelMessage.close:type_name -> tunnel.TcpClose
	6, // 5: tunnel.TunnelMessage.ping:type_name -> tunnel.Ping
	7, // 6: tunnel.TunnelMessage.pong:type_name -> tunnel.Pong
	0, // 7: tunnel.TunnelService.Tunnel:input_type -> tunnel.TunnelMessage
	0, // 8: tunnel.TunnelService.Tunnel:output_type -> tunnel.TunnelMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_Register)(nil),
		(*TunnelMessage_RegisterAck)(nil),
		(*TunnelMessage_Open)(nil),
		(*TunnelMessage_Data)(nil),
		(*TunnelMessage_Close)(nil),
		(*TunnelMessage_Ping)(nil),
		(*TunnelMessage_Pong)(nil),
	}
	file_proto_tunnel_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
