// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/frame.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	// Main WS (signalling)
	FrameType_REGISTER      FrameType = 1
	FrameType_REGISTERED    FrameType = 2
	FrameType_REQUEST       FrameType = 3
	FrameType_REQUEST_ACK   FrameType = 4
	FrameType_REQUEST_ERROR FrameType = 5
	FrameType_PING          FrameType = 6
	FrameType_PONG          FrameType = 7
	// Dedicated WS (per-request)
	FrameType_BODY           FrameType = 10
	FrameType_BODY_END       FrameType = 11
	FrameType_RESPONSE_START FrameType = 12
	FrameType_RESPONSE_BODY  FrameType = 13
	FrameType_RESPONSE_END   FrameType = 14
	FrameType_RESPONSE_ERROR FrameType = 15
	FrameType_WS_DATA        FrameType = 16
	FrameType_WS_CLOSE       FrameType = 17
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0:  "FRAME_TYPE_UNSPECIFIED",
		1:  "REGISTER",
		2:  "REGISTERED",
		3:  "REQUEST",
		4:  "REQUEST_ACK",
		5:  "REQUEST_ERROR",
		6:  "PING",
		7:  "PONG",
		10: "BODY",
		11: "BODY_END",
		12: "RESPONSE_START",
		13: "RESPONSE_BODY",
		14: "RESPONSE_END",
		15: "RESPONSE_ERROR",
		16: "WS_DATA",
		17: "WS_CLOSE",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"REGISTER":               1,
		"REGISTERED":             2,
		"REQUEST":                3,
		"REQUEST_ACK":            4,
		"REQUEST_ERROR":          5,
		"PING":                   6,
		"PONG":                   7,
		"BODY":                   10,
		"BODY_END":               11,
		"RESPONSE_START":         12,
		"RESPONSE_BODY":          13,
		"RESPONSE_END":           14,
		"RESPONSE_ERROR":         15,
		"WS_DATA":                16,
		"WS_CLOSE":               17,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_frame_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_proto_frame_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_frame_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      FrameType              `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.FrameType" json:"type,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Request notification
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]*StringList `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentLength int64                  `protobuf:"varint,6,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	// Response
	Status          int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	ResponseHeaders map[string]*StringList `protobuf:"bytes,8,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Body / data chunk (raw bytes, no base64 needed)
	Chunk []byte `protobuf:"bytes,9,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Error
	Error string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	// Registration
	Domain        string `protobuf:"bytes,11,opt,name=domain,proto3" json:"domain,omitempty"`
	DomainKey     string `protobuf:"bytes,12,opt,name=domain_key,json=domainKey,proto3" json:"domain_key,omitempty"`
	TunnelId      string `protobuf:"bytes,13,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	ServerMessage string `protobuf:"bytes,14,opt,name=server_message,json=serverMessage,proto3" json:"server_message,omitempty"`
	// Tunnel config (sent on registration)
	Config        *TunnelConfig `protobuf:"bytes,15,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *Frame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Frame) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Frame) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Frame) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Frame) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Frame) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Frame) GetResponseHeaders() map[string]*StringList {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *Frame) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *Frame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Frame) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Frame) GetDomainKey() string {
	if x != nil {
		return x.DomainKey
	}
	return ""
}

func (x *Frame) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *Frame) GetServerMessage() string {
	if x != nil {
		return x.ServerMessage
	}
	return ""
}

func (x *Frame) GetConfig() *TunnelConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_proto_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_proto_frame_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type TunnelConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrent    int32                  `protobuf:"varint,1,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	RequestTimeoutMs int32                  `protobuf:"varint,2,opt,name=request_timeout_ms,json=requestTimeoutMs,proto3" json:"request_timeout_ms,omitempty"`
	BackendTimeoutMs int32                  `protobuf:"varint,3,opt,name=backend_timeout_ms,json=backendTimeoutMs,proto3" json:"backend_timeout_ms,omitempty"`
	Reconnect        *ReconnectConfig       `protobuf:"bytes,4,opt,name=reconnect,proto3" json:"reconnect,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TunnelConfig) Reset() {
	*x = TunnelConfig{}
	mi := &file_proto_frame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelConfig) ProtoMessage() {}

func (x *TunnelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelConfig.ProtoReflect.Descriptor instead.
func (*TunnelConfig) Descriptor() ([]byte, []int) {
	return file_proto_frame_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelConfig) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *TunnelConfig) GetRequestTimeoutMs() int32 {
	if x != nil {
		return x.RequestTimeoutMs
	}
	return 0
}

func (x *TunnelConfig) GetBackendTimeoutMs() int32 {
	if x != nil {
		return x.BackendTimeoutMs
	}
	return 0
}

func (x *TunnelConfig) GetReconnect() *ReconnectConfig {
	if x != nil {
		return x.Reconnect
	}
	return nil
}

type ReconnectConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	InitialDelayMs int32                  `protobuf:"varint,2,opt,name=initial_delay_ms,json=initialDelayMs,proto3" json:"initial_delay_ms,omitempty"`
	MaxDelayMs     int32                  `protobuf:"varint,3,opt,name=max_delay_ms,json=maxDelayMs,proto3" json:"max_delay_ms,omitempty"`
	Multiplier     float64                `protobuf:"fixed64,4,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Jitter         bool                   `protobuf:"varint,6,opt,name=jitter,proto3" json:"jitter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconnectConfig) Reset() {
	*x = ReconnectConfig{}
	mi := &file_proto_frame_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectConfig) ProtoMessage() {}

func (x *ReconnectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frame_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectConfig.ProtoReflect.Descriptor instead.
func (*ReconnectConfig) Descriptor() ([]byte, []int) {
	return file_proto_frame_proto_rawDescGZIP(), []int{3}
}

func (x *ReconnectConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ReconnectConfig) GetInitialDelayMs() int32 {
	if x != nil {
		return x.InitialDelayMs
	}
	return 0
}

func (x *ReconnectConfig) GetMaxDelayMs() int32 {
	if x != nil {
		return x.MaxDelayMs
	}
	return 0
}

func (x *ReconnectConfig) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *ReconnectConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *ReconnectConfig) GetJitter() bool {
	if x != nil {
		return x.Jitter
	}
	return false
}

var File_proto_frame_proto protoreflect.FileDescriptor

const file_proto_frame_proto_rawDesc = "" +
	"\n" +
	"\x11proto/frame.proto\x12\bprotocol\"\xc6\x05\n" +
	"\x05Frame\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.protocol.FrameTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x126\n" +
	"\aheaders\x18\x05 \x03(\v2\x1c.protocol.Frame.HeadersEntryR\aheaders\x12%\n" +
	"\x0econtent_length\x18\x06 \x01(\x03R\rcontentLength\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12O\n" +
	"\x10response_headers\x18\b \x03(\v2$.protocol.Frame.ResponseHeadersEntryR\x0fresponseHeaders\x12\x14\n" +
	"\x05chunk\x18\t \x01(\fR\x05chunk\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x16\n" +
	"\x06domain\x18\v \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"domain_key\x18\f \x01(\tR\tdomainKey\x12\x1b\n" +
	"\ttunnel_id\x18\r \x01(\tR\btunnelId\x12%\n" +
	"\x0eserver_message\x18\x0e \x01(\tR\rserverMessage\x12.\n" +
	"\x06config\x18\x0f \x01(\v2\x16.protocol.TunnelConfigR\x06config\x1aP\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protocol.StringListR\x05value:\x028\x01\x1aX\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protocol.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xca\x01\n" +
	"\fTunnelConfig\x12%\n" +
	"\x0emax_concurrent\x18\x01 \x01(\x05R\rmaxConcurrent\x12,\n" +
	"\x12request_timeout_ms\x18\x02 \x01(\x05R\x10requestTimeoutMs\x12,\n" +
	"\x12backend_timeout_ms\x18\x03 \x01(\x05R\x10backendTimeoutMs\x127\n" +
	"\treconnect\x18\x04 \x01(\v2\x19.protocol.ReconnectConfigR\treconnect\"\xd0\x01\n" +
	"\x0fReconnectConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12(\n" +
	"\x10initial_delay_ms\x18\x02 \x01(\x05R\x0einitialDelayMs\x12 \n" +
	"\fmax_delay_ms\x18\x03 \x01(\x05R\n" +
	"maxDelayMs\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x01R\n" +
	"multiplier\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x12\x16\n" +
	"\x06jitter\x18\x06 \x01(\bR\x06jitter*\x8a\x02\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"REGISTERED\x10\x02\x12\v\n" +
	"\aREQUEST\x10\x03\x12\x0f\n" +
	"\vREQUEST_ACK\x10\x04\x12\x11\n" +
	"\rREQUEST_ERROR\x10\x05\x12\b\n" +
	"\x04PING\x10\x06\x12\b\n" +
	"\x04PONG\x10\a\x12\b\n" +
	"\x04BODY\x10\n" +
	"\x12\f\n" +
	"\bBODY_END\x10\v\x12\x12\n" +
	"\x0eRESPONSE_START\x10\f\x12\x11\n" +
	"\rRESPONSE_BODY\x10\r\x12\x10\n" +
	"\fRESPONSE_END\x10\x0e\x12\x12\n" +
	"\x0eRESPONSE_ERROR\x10\x0f\x12\v\n" +
	"\aWS_DATA\x10\x10\x12\f\n" +
	"\bWS_CLOSE\x10\x11B3Z1github.com/kaenova/http-tunnels/internal/protocolb\x06proto3"

var (
	file_proto_frame_proto_rawDescOnce sync.Once
	file_proto_frame_proto_rawDescData []byte
)

func file_proto_frame_proto_rawDescGZIP() []byte {
	file_proto_frame_proto_rawDescOnce.Do(func() {
		file_proto_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_frame_proto_rawDesc), len(file_proto_frame_proto_rawDesc)))
	})
	return file_proto_frame_proto_rawDescData
}

var file_proto_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_frame_proto_goTypes = []any{
	(FrameType)(0),          // 0: protocol.FrameType
	(*Frame)(nil),           // 1: protocol.Frame
	(*StringList)(nil),      // 2: protocol.StringList
	(*TunnelConfig)(nil),    // 3: protocol.TunnelConfig
	(*ReconnectConfig)(nil), // 4: protocol.ReconnectConfig
	nil,                     // 5: protocol.Frame.HeadersEntry
	nil,                     // 6: protocol.Frame.ResponseHeadersEntry
}
var file_proto_frame_proto_depIdxs = []int32{
	0, // 0: protocol.Frame.type:type_name -> protocol.FrameType
	5, // 1: protocol.Frame.headers:type_name -> protocol.Frame.HeadersEntry
	6, // 2: protocol.Frame.response_headers:type_name -> protocol.Frame.ResponseHeadersEntry
	3, // 3: protocol.Frame.config:type_name -> protocol.TunnelConfig
	4, // 4: protocol.TunnelConfig.reconnect:type_name -> protocol.ReconnectConfig
	2, // 5: protocol.Frame.HeadersEntry.value:type_name -> protocol.StringList
	2, // 6: protocol.Frame.ResponseHeadersEntry.value:type_name -> protocol.StringList
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_frame_proto_init() }
func file_proto_frame_proto_init() {
	if File_proto_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_frame_proto_rawDesc), len(file_proto_frame_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_frame_proto_goTypes,
		DependencyIndexes: file_proto_frame_proto_depIdxs,
		EnumInfos:         file_proto_frame_proto_enumTypes,
		MessageInfos:      file_proto_frame_proto_msgTypes,
	}.Build()
	File_proto_frame_proto = out.File
	file_proto_frame_proto_goTypes = nil
	file_proto_frame_proto_depIdxs = nil
}
