name: Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/server.yaml
      - cmd/server/**
env:
  TAGS: ${{ github.sha }}

  # Please fill this
  DOCKER_REPOSITORY: kaenova/tunnel

jobs:
  Docker-Imaging:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: docker build --tag "$DOCKER_REPOSITORY:$TAGS" --tag "$DOCKER_REPOSITORY:latest" -f Dockerfile .

      - name: Dockerhub Push
        run: docker push "$DOCKER_REPOSITORY" --all-tags